# Generated by Django 5.1.6 on 2025-02-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('integration_type', models.CharField(choices=[('interval', 'Interval'), ('modifier', 'Modifier'), ('output', 'Output')], max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityIntegration',
            fields=[
                ('coreintegration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.coreintegration')),
                ('monitored_events', models.JSONField(default=list)),
                ('scan_schedule', models.JSONField(default=dict)),
            ],
            bases=('core.coreintegration',),
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('source_ip', models.GenericIPAddressField()),
                ('details', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreintegration')),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabilityScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(max_length=50)),
                ('results', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreintegration')),
            ],
        ),
    ]
