# Generated by Django 5.1.6 on 2025-02-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertRule',
        ),
        migrations.DeleteModel(
            name='NotificationChannel',
        ),
    ]
